# Generated by Django 3.2.9 on 2023-03-26 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teachers',
            old_name='Teacher_Eudcation',
            new_name='Teacher_Education',
        ),
    ]
