# Generated by Django 3.2.9 on 2023-03-25 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('Roll', models.IntegerField()),
                ('Age', models.IntegerField()),
                ('Address', models.CharField(max_length=255)),
                ('Phone', models.IntegerField()),
            ],
        ),
    ]
